version: '3.7'
services:
  webapp:
    image: netmaiesta/django:3.4
    container_name: dtest
    volumes:
      - .:/usr/src/app/django/site
      - ./data:/data
    ports:
      - '5000:5000'
      - '27017:27017'
    entrypoint: /code/entrypoint.sh
