version: '3.7'

services:

  webapp:
    image: netmaiesta/django:1
    container_name: mycontainer
    volumes:
      - .:/usr/src/app/django/mysite
    ports:
      - '5000:5000'
    entrypoint:
      - python3
      - /usr/src/app/django/mysite/manage.py 
      - runserver
      - 0.0.0.0:5000
